//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class unimoVerInfoEntities : DbContext
{
    public unimoVerInfoEntities()
        : base("name=unimoVerInfoEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<alumnosFromGE> alumnosFromGES { get; set; }
    public virtual DbSet<dataVer1> dataVer1 { get; set; }
    public virtual DbSet<dataVer2> dataVer2 { get; set; }
    public virtual DbSet<estado> estadoes { get; set; }
    public virtual DbSet<pai> pais { get; set; }
    public virtual DbSet<dataVer2ERR> dataVer2ERR { get; set; }
    public virtual DbSet<plantel> plantels { get; set; }
    public virtual DbSet<BitacoraVI> BitacoraVIs { get; set; }
}
