//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class alumnosFromGE
{
    public double NUMEROALUMNO { get; set; }
    public string PATERNO { get; set; }
    public string MATERNO { get; set; }
    public string NOMBRE { get; set; }
    public string NIVEL { get; set; }
    public Nullable<double> GRADO { get; set; }
    public Nullable<double> MATRICULA { get; set; }
    public string CLAVE_CIUDADANA { get; set; }
    public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
    public string DOMICILIO { get; set; }
    public string CP { get; set; }
    public string CIUDAD { get; set; }
    public string ESTADO { get; set; }
    public string TELEFONO { get; set; }
    public string CELULAR { get; set; }
    public string ESTADO_CIVIL { get; set; }
    public string EMAIL { get; set; }
    public string LUGAR_NACIMIENTO { get; set; }
    public string ESTADO_NACIMIENTO { get; set; }
    public string NACIONALIDAD { get; set; }
    public string ESCUELA_PROCEDENCIA { get; set; }
    public string ESTADO_ESCOLARIDAD { get; set; }
    public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
    public string GENERO { get; set; }
    public Nullable<int> PLANTEL { get; set; }
    public string CODIGOGRUPO { get; set; }
}

public partial class BitacoraVI
{
    public long IdBitacora { get; set; }
    public Nullable<double> MATRICULA { get; set; }
    public Nullable<double> NUMEROALUMNO { get; set; }
    public string MOVIMIENTO { get; set; }
    public System.DateTime FECHA { get; set; }
}

public partial class dataVer1
{
    public double NUMEROALUMNO { get; set; }
    public string PATERNO { get; set; }
    public string MATERNO { get; set; }
    public string NOMBRE { get; set; }
    public string NIVEL { get; set; }
    public Nullable<double> GRADO { get; set; }
    public Nullable<double> MATRICULA { get; set; }
    public string CLAVE_CIUDADANA { get; set; }
    public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
    public string CP { get; set; }
    public string CIUDAD { get; set; }
    public string ESTADO { get; set; }
    public string TELEFONO { get; set; }
    public string CELULAR { get; set; }
    public string ESTADO_CIVIL { get; set; }
    public string EMAIL { get; set; }
    public string LUGAR_NACIMIENTO { get; set; }
    public string ESTADO_NACIMIENTO { get; set; }
    public string NACIONALIDAD { get; set; }
    public string ESCUELA_PROCEDENCIA { get; set; }
    public string ESTADO_ESCOLARIDAD { get; set; }
    public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
    public string GENERO { get; set; }
    public Nullable<int> PLANTEL { get; set; }
    public string CALLE { get; set; }
    public string NUMINT { get; set; }
    public string NUMEXT { get; set; }
    public string COLONIA { get; set; }
    public Nullable<int> PAIS { get; set; }
    public string CODIGOGRUPO { get; set; }
    public string CICLO { get; set; }
    public Nullable<System.DateTime> FECHAREVISION { get; set; }
}

public partial class dataVer2
{
    public double NUMEROALUMNO { get; set; }
    public string PATERNO { get; set; }
    public string MATERNO { get; set; }
    public string NOMBRE { get; set; }
    public string NIVEL { get; set; }
    public Nullable<double> GRADO { get; set; }
    public Nullable<double> MATRICULA { get; set; }
    public string CLAVE_CIUDADANA { get; set; }
    public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
    public string CP { get; set; }
    public string CIUDAD { get; set; }
    public string ESTADO { get; set; }
    public string TELEFONO { get; set; }
    public string CELULAR { get; set; }
    public string ESTADO_CIVIL { get; set; }
    public string EMAIL { get; set; }
    public string LUGAR_NACIMIENTO { get; set; }
    public string ESTADO_NACIMIENTO { get; set; }
    public string NACIONALIDAD { get; set; }
    public string ESCUELA_PROCEDENCIA { get; set; }
    public string ESTADO_ESCOLARIDAD { get; set; }
    public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
    public string GENERO { get; set; }
    public Nullable<int> PLANTEL { get; set; }
    public string CALLE { get; set; }
    public string NUMINT { get; set; }
    public string NUMEXT { get; set; }
    public string COLONIA { get; set; }
    public Nullable<int> PAIS { get; set; }
    public string CODIGOGRUPO { get; set; }
    public string CICLO { get; set; }
    public Nullable<System.DateTime> FECHAREVISION { get; set; }
}

public partial class dataVer2ERR
{
    public double NUMEROALUMNO { get; set; }
    public Nullable<short> PATERNO { get; set; }
    public Nullable<short> MATERNO { get; set; }
    public Nullable<short> NOMBRE { get; set; }
    public Nullable<short> NIVEL { get; set; }
    public Nullable<short> GRADO { get; set; }
    public Nullable<short> CLAVE_CIUDADANA { get; set; }
    public Nullable<short> ESTADO_CIVIL { get; set; }
    public Nullable<short> FECHA_NACIMIENTO { get; set; }
    public Nullable<short> CP { get; set; }
    public Nullable<short> CIUDAD { get; set; }
    public Nullable<short> ESTADO { get; set; }
    public Nullable<short> TELEFONO { get; set; }
    public Nullable<short> CELULAR { get; set; }
    public Nullable<short> EMAIL { get; set; }
    public Nullable<short> LUGAR_NACIMIENTO { get; set; }
    public Nullable<short> ESTADO_NACIMIENTO { get; set; }
    public Nullable<short> NACIONALIDAD { get; set; }
    public Nullable<short> ESCUELA_PROCEDENCIA { get; set; }
    public Nullable<short> ESTADO_ESCOLARIDAD { get; set; }
    public Nullable<short> FECHA_INGRESO { get; set; }
    public Nullable<short> GENERO { get; set; }
    public Nullable<short> PLANTEL { get; set; }
    public Nullable<short> CALLE { get; set; }
    public Nullable<short> NUMINT { get; set; }
    public Nullable<short> NUMEXT { get; set; }
    public Nullable<short> COLONIA { get; set; }
    public Nullable<short> PAIS { get; set; }
    public Nullable<short> CODIGOGRUPO { get; set; }
    public System.DateTime TIMESTAMP { get; set; }
    public Nullable<short> CICLO { get; set; }
}

public partial class estado
{
    public int id_estado { get; set; }
    public int id_pais { get; set; }
    public string estado1 { get; set; }
    public string edoGES { get; set; }

    public virtual pai pai { get; set; }
}

public partial class pai
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public pai()
    {
        this.estadoes = new HashSet<estado>();
    }

    public int id_pais { get; set; }
    public string pais { get; set; }
    public short haya { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<estado> estadoes { get; set; }
}

public partial class plantel
{
    public int id_plantel { get; set; }
    public int IdGES { get; set; }
    public string nombre_plantel { get; set; }
    public Nullable<int> id_director { get; set; }
    public Nullable<int> id_departamento { get; set; }
    public Nullable<short> activo { get; set; }
    public string calle { get; set; }
    public string colonia { get; set; }
    public string ciudad { get; set; }
    public string estado { get; set; }
    public string cp { get; set; }
    public string pais { get; set; }
}
